<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Modules\Accounting\Application\PostingEngine;
use App\Modules\Insurance\Regulatory\Application\Provisions\TechnicalProvisionService;
use App\Modules\Insurance\Regulatory\Application\RegulatoryPeriod;
use App\Modules\Insurance\Regulatory\Application\Returns\RegulatoryReturnService;
use App\Modules\Platform\Tenancy\BusinessClock;
use App\Modules\Platform\Tenancy\TenantContext;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use RuntimeException;

/**
 * Market gap G5 demo, run inside the Part A story (Padma General Insurance, tenant context set):
 * - Paid claims from before the system (the legacy claims register, ASSUMPTION A-265): motor for seven accident quarters from Q4 2024 and fire for five from Q2 2025,
 *   so motor and fire have a paid chain-ladder triangle; marine has no history and uses the percentage method.
 * - The Q3 2026 technical provisions run: prepared and reviewed by the finance manager, approved and posted by the CFO (IBNR_PROVISION per class, dated 30 September).
 * - The Q3 2026 returns set generated by the finance manager; the agent and producer register summary reviewed and marked filed with IDRA (demo reference).
 */
final class RegulatoryDemoSeeder
{
    /** Motor: ultimate paid per accident quarter (BDT minor) and the share paid in each development quarter (%). */
    private const MOTOR = ['ultimates' => [1_60_000_00, 1_85_000_00, 1_40_000_00, 2_10_000_00, 1_95_000_00, 1_70_000_00, 2_25_000_00], 'pattern' => [45, 30, 15, 7, 3]];

    /** Fire: fewer, larger losses paid more slowly. */
    private const FIRE = ['ultimates' => [3_20_000_00, 90_000_00, 4_50_000_00, 1_20_000_00, 2_60_000_00], 'pattern' => [30, 40, 20, 10]];

    public const FILING_REFERENCE = 'IDRA/NL/2026/Q3/AR-0147';

    /** @param array<string, string> $users role code → user id */
    public function run(string $entityId, array $users): void
    {
        $this->history($entityId, 'motor', 2024 * 4 + 3, self::MOTOR['ultimates'], self::MOTOR['pattern']);
        $this->history($entityId, 'fire', 2025 * 4 + 1, self::FIRE['ultimates'], self::FIRE['pattern']);
        $quarter = RegulatoryPeriod::fromKey('2026-Q3');

        $provisions = app(TechnicalProvisionService::class);
        $run = $provisions->prepare($entityId, $quarter, [], $users['finance_manager']);
        $provisions->review($run, $users['finance_manager']);
        $provisions->approve($run, $users['cfo']);
        foreach (DB::table('accounting_events')->where('status', 'queued')->orderBy('created_at')->orderBy('id')->pluck('id') as $eventId) {
            app(PostingEngine::class)->post((string) $eventId);
        }
        $failed = DB::table('accounting_events')->where('source_type', 'technical_provision_run')->where('status', 'failed')->value('failure_reason');
        if ($failed !== null) {
            throw new RuntimeException("Demo technical provisions did not post: {$failed}");
        }

        $returns = app(RegulatoryReturnService::class);
        $returns->generate($entityId, $quarter, $users['finance_manager']);
        $register = (string) DB::table('regulatory_returns')->where('entity_id', $entityId)->where('period_key', $quarter->key)->where('form_code', 'agent_register')->value('id');
        $returns->review($register, $users['finance_manager']);
        $returns->file($register, app(BusinessClock::class)->today($entityId), self::FILING_REFERENCE, $users['finance_manager']);
    }

    /**
     * @param list<int> $ultimates one per accident quarter, oldest first
     * @param list<int> $pattern percentage paid in development quarters 0, 1, 2, …
     */
    private function history(string $entityId, string $class, int $firstQuarter, array $ultimates, array $pattern): void
    {
        $lastHistoryQuarter = 2026 * 4 + 1; // Q2 2026: the system's own claim payments start in Q3 2026
        $start = fn (int $index): string => sprintf('%d-%02d-01', intdiv($index, 4), $index % 4 * 3 + 1);
        foreach ($ultimates as $i => $ultimate) {
            $accident = $firstQuarter + $i;
            foreach ($pattern as $dev => $percent) {
                if ($accident + $dev > $lastHistoryQuarter) {
                    break;
                }
                DB::table('claims_paid_history')->insert(['id' => (string) Str::uuid7(), 'tenant_id' => TenantContext::id(), 'entity_id' => $entityId, 'class' => $class,
                    'accident_quarter_start' => $start($accident), 'paid_quarter_start' => $start($accident + $dev), 'paid_minor' => intdiv($ultimate * $percent, 100),
                    'source' => 'legacy_import', 'created_at' => now()]);
            }
        }
    }
}
