-- App connects as a NON-owner role so FORCE ROW LEVEL SECURITY applies (design §8.6).
CREATE ROLE erp_app LOGIN PASSWORD 'erp';
GRANT CONNECT ON DATABASE erp TO erp_app;
GRANT USAGE ON SCHEMA public TO erp_app;
ALTER DEFAULT PRIVILEGES FOR ROLE erp_owner IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO erp_app;
ALTER DEFAULT PRIVILEGES FOR ROLE erp_owner IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO erp_app;
CREATE DATABASE erp_test OWNER erp_owner;
GRANT CONNECT ON DATABASE erp_test TO erp_app;
