<script setup lang="ts">
import { router, useForm } from '@inertiajs/vue3';
import { ref } from 'vue';
import FormError from '@/components/FormError.vue';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import AppLayout from '@/layouts/AppLayout.vue';

const props = defineProps<{ twoFactor: { enabled: boolean; confirmed: boolean } }>();

const passwordForm = useForm({ current_password: '', password: '', password_confirmation: '' });
const confirmForm = useForm({ code: '' });
const qrSvg = ref<string | null>(null);
const recoveryCodes = ref<string[]>([]);

async function getJson<T>(url: string): Promise<T> {
    const response = await fetch(url, { headers: { Accept: 'application/json' }, credentials: 'same-origin' });
    return (await response.json()) as T;
}

async function loadQrCode(): Promise<void> {
    qrSvg.value = (await getJson<{ svg: string }>('/user/two-factor-qr-code')).svg;
}

async function showRecoveryCodes(): Promise<void> {
    recoveryCodes.value = await getJson<string[]>('/user/two-factor-recovery-codes');
}

function updatePassword(): void {
    passwordForm.put('/user/password', { errorBag: 'updatePassword', preserveScroll: true, onSuccess: () => passwordForm.reset() });
}

function enableTwoFactor(): void {
    router.post('/user/two-factor-authentication', {}, { preserveScroll: true, onSuccess: () => void loadQrCode() });
}

function confirmTwoFactor(): void {
    confirmForm.post('/user/confirmed-two-factor-authentication', {
        errorBag: 'confirmTwoFactorAuthentication',
        preserveScroll: true,
        onSuccess: () => {
            qrSvg.value = null;
            void showRecoveryCodes();
        },
    });
}

function disableTwoFactor(): void {
    router.delete('/user/two-factor-authentication', { preserveScroll: true, onSuccess: () => (recoveryCodes.value = []) });
}
</script>

<template>
    <AppLayout title="Security">
        <h1 class="mb-6 text-3xl font-bold">Security</h1>
        <div class="grid gap-6 lg:grid-cols-2">
            <Card>
                <h2 class="text-lg font-semibold">Password</h2>
                <form class="mt-4 grid gap-4" @submit.prevent="updatePassword">
                    <div class="grid gap-1.5">
                        <Label for="current_password">Current password</Label>
                        <Input id="current_password" v-model="passwordForm.current_password" type="password" autocomplete="current-password" />
                        <FormError :message="passwordForm.errors.current_password" />
                    </div>
                    <div class="grid gap-1.5">
                        <Label for="new_password">New password</Label>
                        <Input id="new_password" v-model="passwordForm.password" type="password" autocomplete="new-password" />
                        <FormError :message="passwordForm.errors.password" />
                    </div>
                    <div class="grid gap-1.5">
                        <Label for="new_password_confirmation">Confirm new password</Label>
                        <Input id="new_password_confirmation" v-model="passwordForm.password_confirmation" type="password" autocomplete="new-password" />
                    </div>
                    <Button type="submit" :disabled="passwordForm.processing" class="justify-self-start">Change password</Button>
                    <p v-if="passwordForm.recentlySuccessful" class="text-sm text-green">Password changed.</p>
                </form>
            </Card>

            <Card>
                <h2 class="text-lg font-semibold">Two-factor authentication</h2>
                <p class="mt-1 text-sm text-ivory-dim">
                    {{ props.twoFactor.confirmed ? 'On. You are asked for a code from your authenticator app when you sign in.' : 'Off. Add a code from an authenticator app to every sign-in.' }}
                </p>

                <div v-if="!props.twoFactor.enabled" class="mt-4">
                    <Button @click="enableTwoFactor">Turn on</Button>
                </div>

                <form v-else-if="!props.twoFactor.confirmed" class="mt-4 grid gap-4" @submit.prevent="confirmTwoFactor">
                    <p class="text-sm text-ivory-dim">Scan the code with your authenticator app, then enter the 6-digit code it shows.</p>
                    <!-- SVG generated by the server for this user -->
                    <div v-if="qrSvg" class="w-fit rounded-md bg-ivory p-3" v-html="qrSvg" />
                    <Button v-else variant="ghost" class="justify-self-start" @click="loadQrCode">Show QR code</Button>
                    <div class="grid gap-1.5">
                        <Label for="code">Code</Label>
                        <Input id="code" v-model="confirmForm.code" inputmode="numeric" autocomplete="one-time-code" />
                        <FormError :message="confirmForm.errors.code" />
                    </div>
                    <div class="flex gap-2">
                        <Button type="submit" :disabled="confirmForm.processing">Confirm</Button>
                        <Button variant="ghost" @click="disableTwoFactor">Cancel</Button>
                    </div>
                </form>

                <div v-else class="mt-4 grid gap-4">
                    <div v-if="recoveryCodes.length" class="rounded-md border border-line bg-surface-raised p-3">
                        <p class="mb-2 text-sm text-ivory-dim">Store these recovery codes somewhere safe. Each works once.</p>
                        <ul class="grid grid-cols-2 gap-1 font-mono text-sm">
                            <li v-for="code in recoveryCodes" :key="code">{{ code }}</li>
                        </ul>
                    </div>
                    <div class="flex flex-wrap gap-2">
                        <Button variant="ghost" @click="showRecoveryCodes">Show recovery codes</Button>
                        <Button variant="ghost" @click="disableTwoFactor">Turn off</Button>
                    </div>
                </div>
            </Card>
        </div>
    </AppLayout>
</template>
