<?php

declare(strict_types=1);

use App\Modules\Platform\Database\RowLevelSecurity;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Fix F2 (market cross-check G2, Part A step 5): documents attached to a business object (claim, receipt, policy; later generated PDFs,
 * docs/rating-quotation-documents-design.md §3). A document is evidence, so its row is append-only, like audit_events, and its file lives
 * under its SHA-256 on the private documents disk: a stored file is never overwritten.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('stored_documents', function (Blueprint $t): void {
            $t->uuid('id')->primary();
            $t->uuid('tenant_id')->index();
            $t->string('object_type', 40); // claim|receipt|policy (the audit subject type)
            $t->uuid('object_id');
            $t->string('original_name', 255);
            $t->string('mime', 127);
            $t->bigInteger('size_bytes');
            $t->char('sha256', 64);
            $t->string('disk', 40);
            $t->string('storage_path', 500);
            $t->string('description', 500)->nullable();
            $t->uuid('uploaded_by')->nullable(); // null = generated by the system
            $t->timestampTz('uploaded_at');
            $t->index(['tenant_id', 'object_type', 'object_id']);
        });
        RowLevelSecurity::enable('stored_documents');

        DB::unprepared(<<<'SQL'
ALTER TABLE stored_documents
  ADD CONSTRAINT stored_documents_sha256_hex CHECK (sha256 ~ '^[0-9a-f]{64}$'),
  ADD CONSTRAINT stored_documents_size_positive CHECK (size_bytes > 0),
  ADD CONSTRAINT stored_documents_path_has_hash CHECK (strpos(storage_path, sha256) > 0);

CREATE OR REPLACE FUNCTION protect_stored_documents() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'DOCUMENT_APPEND_ONLY: stored document % cannot be %', OLD.id, lower(TG_OP) USING ERRCODE = 'check_violation';
END $$;

CREATE TRIGGER stored_documents_append_only BEFORE UPDATE OR DELETE ON stored_documents
  FOR EACH ROW EXECUTE FUNCTION protect_stored_documents();
SQL);
    }

    public function down(): void
    {
        DB::unprepared('DROP TRIGGER IF EXISTS stored_documents_append_only ON stored_documents; DROP FUNCTION IF EXISTS protect_stored_documents;');
        Schema::dropIfExists('stored_documents');
    }
};
