<script setup lang="ts">
import { useForm } from '@inertiajs/vue3';
import { ref } from 'vue';
import SelectInput from '@/components/forms/SelectInput.vue';
import type { DocumentGeneration } from '@/components/object/types';
import { formatDate, formatFileSize } from '@/lib/format';

/**
 * Slice R8: printable documents on the Documents tab — generate the schedule, an endorsement or a receipt from the active template in English or
 * Bangla, and every version generated (never overwritten; generating again adds a version). Each PDF is also a stored document of the page.
 */
const props = defineProps<{ generation: DocumentGeneration }>();

const locale = ref(props.generation.locales[0]?.value ?? 'en');
const form = useForm<{ template_code: string; object_id: string | null; locale: string }>({ template_code: '', object_id: null, locale: 'en' });
const running = ref<string | null>(null);

function generate(action: DocumentGeneration['actions'][number]): void {
    if (!props.generation.url) return;
    running.value = `${action.template_code}:${action.object_id ?? ''}`;
    form.template_code = action.template_code;
    form.object_id = action.object_id;
    form.locale = locale.value;
    form.post(props.generation.url, { preserveScroll: true, onFinish: () => (running.value = null) });
}

const language = (code: string) => props.generation.locales.find((l) => l.value === code)?.label ?? code;
</script>

<template>
    <section class="grid gap-3" aria-labelledby="generated-documents-title">
        <h2 id="generated-documents-title" class="text-ui font-medium">Printed documents</h2>
        <div v-if="generation.actions.length" class="flex flex-wrap items-end gap-2">
            <label class="grid gap-1 text-dense text-ink-2">
                Language
                <SelectInput id="generation-locale" v-model="locale" :options="generation.locales" class="w-32" />
            </label>
            <button
                v-for="action in generation.actions"
                :key="`${action.template_code}:${action.object_id ?? ''}`"
                type="button"
                :disabled="form.processing"
                class="inline-flex h-8 items-center rounded-control border border-line-control px-3 text-ui hover:bg-surface-2 disabled:opacity-50"
                @click="generate(action)"
            >
                {{ running === `${action.template_code}:${action.object_id ?? ''}` ? 'Generating…' : action.label }}
            </button>
        </div>
        <p v-if="(form.errors as Record<string, string>).form" class="text-dense text-danger" role="alert">{{ (form.errors as Record<string, string>).form }}</p>

        <div v-if="generation.history.length" class="overflow-x-auto border border-line">
            <table class="w-full table-fixed border-separate border-spacing-0 text-dense">
                <colgroup><col /><col style="width: 70px" /><col style="width: 90px" /><col style="width: 160px" /><col style="width: 110px" /><col style="width: 120px" /><col style="width: 90px" /></colgroup>
                <thead class="bg-surface-2 text-ink-2">
                    <tr class="h-(--row-h)">
                        <th class="border-b border-line px-3 text-left font-medium">Document</th>
                        <th class="border-b border-line px-3 text-right font-medium">Version</th>
                        <th class="border-b border-line px-3 text-left font-medium">Language</th>
                        <th class="border-b border-line px-3 text-left font-medium">Generated by</th>
                        <th class="border-b border-line px-3 text-left font-medium">Date</th>
                        <th class="border-b border-line px-3 text-left font-medium">Reference</th>
                        <th class="border-b border-line px-3"><span class="sr-only">Download</span></th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="row in generation.history" :key="row.id" class="h-(--row-h) align-top">
                        <td class="border-b border-line px-3 py-1.5">
                            <p class="truncate" :title="`${row.title} ${row.number ?? ''}`">{{ row.title }} <span class="text-ink-2">{{ row.number }}</span></p>
                            <p class="truncate text-ink-2">Template version {{ row.template_version }} · {{ formatFileSize(row.size_bytes) }}</p>
                        </td>
                        <td class="border-b border-line px-3 py-1.5 text-right tabular-nums">{{ row.version }}</td>
                        <td class="border-b border-line px-3 py-1.5">{{ language(row.locale) }}</td>
                        <td class="truncate border-b border-line px-3 py-1.5">{{ row.rendered_by }}</td>
                        <td class="border-b border-line px-3 py-1.5">{{ formatDate(row.rendered_at) }}</td>
                        <td class="border-b border-line px-3 py-1.5 tabular-nums" :title="`SHA-256 of the PDF ${row.sha256}`">{{ row.reference }}</td>
                        <td class="border-b border-line px-3 py-1.5 text-right"><a :href="row.url" class="text-accent-text hover:underline" :aria-label="`Download ${row.title} version ${row.version}`">Download</a></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <p v-else class="text-ui text-ink-2">{{ generation.actions.length ? 'Nothing printed yet; choose a document above.' : 'Nothing printed yet.' }}</p>
    </section>
</template>
